import { motion } from 'framer-motion';
import { imageUrl } from '../api';
import { moodGradient, prettyForm, prettyMood } from '../lib/mood';
import { posterAspect } from '../lib/poster';
import { longDate } from '../lib/schedule';
import type { Capsule } from '../types';

/** Today's work. The image and the words are the interface. */
export function CapsuleHero({ capsule }: { capsule: Capsule }) {
  const { context } = capsule;

  return (
    <motion.article
      id="today"
      initial={{ opacity: 0, y: 16 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.7, ease: [0.16, 1, 0.3, 1] }}
      className="mx-auto max-w-6xl scroll-mt-28 px-5 pt-24 sm:px-8 sm:pt-32"
    >
      <div className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <span className="label">Today&apos;s capsule</span>
          <h2 className="mt-2 font-display text-2xl font-light text-white sm:text-3xl">
            <time dateTime={capsule.date}>{longDate(capsule.date)}</time>
          </h2>
        </div>

        <div className="flex flex-wrap gap-2">
          <span className="pill border-pulse-400/25 bg-pulse-500/10 text-pulse-300">
            {capsule.theme}
          </span>
          <span className="pill">{prettyMood(capsule.mood)}</span>
          <span className="pill">{prettyForm(capsule.form)}</span>
        </div>
      </div>

      {/* Stacked rather than side-by-side: the poster is landscape, so a column
          would render it small. */}
      <div className="mt-8 grid gap-6 lg:gap-8">
        <CapsuleImage capsule={capsule} />

        <div className="card flex flex-col p-6 sm:p-9">
          <h3 className="font-display text-[1.7rem] font-normal leading-tight text-white sm:text-[2.1rem]">
            {capsule.title}
          </h3>

          <div className="mt-5 h-px w-14 bg-gradient-to-r from-pulse-400/70 to-transparent" />

          <div className="story-prose mt-6 flex-1">{capsule.story}</div>

          <blockquote
            className="mt-8 border-l-2 border-ember-400/50 pl-5 font-display text-lg
                       font-light italic leading-relaxed text-ember-300/90"
          >
            {capsule.quote}
          </blockquote>

          <footer className="mt-7 flex flex-wrap items-center gap-x-4 gap-y-2 border-t border-white/[0.07] pt-5 text-xs text-slate-500">
            <span>{context.location}</span>
            <Dot />
            <span>{context.season}</span>
            {context.condition && (
              <>
                <Dot />
                <span>
                  {context.condition}
                  {typeof context.temp_c === 'number' && `, ${context.temp_c}°C`}
                </span>
              </>
            )}
          </footer>
        </div>
      </div>
    </motion.article>
  );
}

/** Text-only capsules are the agent degrading correctly, so this has to look intentional. */
function CapsuleImage({ capsule }: { capsule: Capsule }) {
  const gradient = moodGradient(capsule.mood);

  if (!capsule.image_key) {
    return (
      <div
        style={posterAspect}
        className={`relative flex items-end overflow-hidden rounded-3xl
                    border border-white/10 bg-gradient-to-br ${gradient}`}
      >
        <div
          aria-hidden="true"
          className="absolute inset-0 animate-drift bg-[radial-gradient(60%_50%_at_30%_20%,rgba(255,255,255,0.13),transparent_70%)]"
        />
        <p className="relative m-6 max-w-xs text-sm leading-relaxed text-white/70">
          The agent published in words alone today. Illustration was unavailable, so it
          shipped the story rather than nothing.
        </p>
      </div>
    );
  }

  return (
    <figure className="relative overflow-hidden rounded-3xl border border-white/10 bg-ink-900">
      <img
        src={imageUrl(capsule.image_key)}
        alt={`${capsule.title} — ${
          capsule.meta.image_kind === 'poster'
            ? 'typographic poster'
            : 'generated artwork'
        } for the theme ${capsule.theme}`}
        loading="eager"
        decoding="async"
        style={posterAspect}
        // contain, not cover: cropping a typographic poster cuts off words.
        className="w-full bg-ink-950 object-contain"
      />
      <div
        aria-hidden="true"
        className="pointer-events-none absolute inset-0 bg-gradient-to-t from-ink-950/70 via-transparent to-transparent"
      />
      <figcaption className="absolute inset-x-0 bottom-0 p-5 text-[11px] text-white/55">
        {visualCredit(capsule)}
      </figcaption>
    </figure>
  );
}

/**
 * Describes the visual accurately. A composed typographic poster is not
 * generated artwork, and implying otherwise would be dishonest — a reader can
 * open the SVG source.
 */
function visualCredit(capsule: Capsule): string {
  if (capsule.meta.image_kind === 'diffusion' && capsule.meta.models.image) {
    return `Generated by ${capsule.meta.models.image}`;
  }
  if (capsule.meta.image_kind === 'poster') {
    return 'Typographic poster composed by the agent';
  }
  return 'Composed by the agent';
}

function Dot() {
  return (
    <span aria-hidden="true" className="h-1 w-1 rounded-full bg-slate-700" />
  );
}
